_target_: src.models.chess_module.ChessModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.cnn.ChessCNN

# compile model for faster training with pytorch 2.0
compile: false

loss_fns:
- _target_: src.models.components.loss_fn.MSELoss
  tag: mse_loss
  weight: 1
