defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: epoch_{epoch:03d}
  monitor: val/total_loss
  verbose: false
  save_last: true
  save_top_k: -1
  mode: min
  auto_insert_metric_name: false
  save_weights_only: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: 20
  save_on_train_epoch_end: null

early_stopping:
  monitor: "val/total_loss"
  patience: 100
  mode: "max"

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: -1

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: epoch
