# @package _global_

defaults:
  - _self_
  - data: chess # choose datamodule with `test_dataloader()` for evaluation
  - model: chess
  - logger: csv
  - trainer: chess_default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
